### ISSUE TITLE
Project failed to run

### ISSUE THREAD

**Issue by TheVinhLuong** [phuonglh/vn.vitk#18]
I have encountered a problem when trying to run the project and couldn't fix it. This is my full log:
```
------------------------------------------------------------------------
Building A Vietnamese Processing Toolkit 3.0
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ vn.vitk ---
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/07/21 23:58:26 INFO SparkContext: Running Spark version 1.6.1
17/07/21 23:58:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/07/21 23:58:28 INFO SecurityManager: Changing view acls to: VinhTL
17/07/21 23:58:28 INFO SecurityManager: Changing modify acls to: VinhTL
17/07/21 23:58:28 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(VinhTL); users with modify permissions: Set(VinhTL)
17/07/21 23:58:30 INFO Utils: Successfully started service 'sparkDriver' on port 4229.
17/07/21 23:58:31 INFO Slf4jLogger: Slf4jLogger started
17/07/21 23:58:31 INFO Remoting: Starting remoting
17/07/21 23:58:31 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.188.2:4243]
17/07/21 23:58:31 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 4243.
17/07/21 23:58:31 INFO SparkEnv: Registering MapOutputTracker
17/07/21 23:58:31 INFO SparkEnv: Registering BlockManagerMaster
17/07/21 23:58:31 INFO DiskBlockManager: Created local directory at C:\Users\VinhTL\AppData\Local\Temp\blockmgr-9fd6d290-d9c6-46bd-90c5-3a29fb5404b2
17/07/21 23:58:32 INFO MemoryStore: MemoryStore started with capacity 1117.9 MB
17/07/21 23:58:32 INFO SparkEnv: Registering OutputCommitCoordinator
17/07/21 23:58:32 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/07/21 23:58:32 INFO SparkUI: Started SparkUI at http://192.168.188.2:4040
17/07/21 23:58:32 INFO Executor: Starting executor ID driver on host localhost
17/07/21 23:58:33 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 4262.
17/07/21 23:58:33 INFO NettyBlockTransferService: Server created on 4262
17/07/21 23:58:33 INFO BlockManagerMaster: Trying to register BlockManager
17/07/21 23:58:33 INFO BlockManagerMasterEndpoint: Registering block manager localhost:4262 with 1117.9 MB RAM, BlockManagerId(driver, localhost, 4262)
17/07/21 23:58:33 INFO BlockManagerMaster: Registered BlockManager
17/07/21 23:58:36 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 107.7 KB, free 107.7 KB)
17/07/21 23:58:36 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 9.8 KB, free 117.5 KB)
17/07/21 23:58:36 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:4262 (size: 9.8 KB, free: 1117.9 MB)
17/07/21 23:58:36 INFO SparkContext: Created broadcast 0 from textFile at Tokenizer.java:83
17/07/21 23:58:38 WARN : Your hostname, VinhTL-PC resolves to a loopback/non-reachable address: fe80:0:0:0:88f7:b80f:643:8365%eth21, but we couldn't find any external IP address!
17/07/21 23:58:43 INFO FileInputFormat: Total input paths to process : 1
17/07/21 23:58:43 INFO SparkContext: Starting job: collect at Tokenizer.java:83
17/07/21 23:58:43 INFO DAGScheduler: Got job 0 (collect at Tokenizer.java:83) with 2 output partitions
17/07/21 23:58:43 INFO DAGScheduler: Final stage: ResultStage 0 (collect at Tokenizer.java:83)
17/07/21 23:58:43 INFO DAGScheduler: Parents of final stage: List()
17/07/21 23:58:43 INFO DAGScheduler: Missing parents: List()
17/07/21 23:58:43 INFO DAGScheduler: Submitting ResultStage 0 (export/dat/tok/regexp.txt MapPartitionsRDD[1] at textFile at Tokenizer.java:83), which has no missing parents
17/07/21 23:58:43 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.1 KB, free 120.6 KB)
17/07/21 23:58:43 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 1811.0 B, free 122.3 KB)
17/07/21 23:58:43 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:4262 (size: 1811.0 B, free: 1117.9 MB)
17/07/21 23:58:43 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
17/07/21 23:58:43 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (export/dat/tok/regexp.txt MapPartitionsRDD[1] at textFile at Tokenizer.java:83)
17/07/21 23:58:43 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
17/07/21 23:58:43 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 2162 bytes)
17/07/21 23:58:43 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, partition 1,PROCESS_LOCAL, 2162 bytes)
17/07/21 23:58:43 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
17/07/21 23:58:43 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
17/07/21 23:58:43 INFO HadoopRDD: Input split: file:/F:/GitHub Reposities/vn.vitk/export/dat/tok/regexp.txt:0+942
17/07/21 23:58:43 INFO HadoopRDD: Input split: file:/F:/GitHub Reposities/vn.vitk/export/dat/tok/regexp.txt:942+942
17/07/21 23:58:43 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
17/07/21 23:58:43 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
17/07/21 23:58:43 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
17/07/21 23:58:43 INFO deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
17/07/21 23:58:43 INFO deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
17/07/21 23:58:43 INFO deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
17/07/21 23:58:43 INFO Executor: Finished task 1.0 in stage 0.0 (TID 1). 2960 bytes result sent to driver
17/07/21 23:58:43 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 3058 bytes result sent to driver
17/07/21 23:58:43 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 374 ms on localhost (1/2)
17/07/21 23:58:43 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 321 ms on localhost (2/2)
17/07/21 23:58:43 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
17/07/21 23:58:43 INFO DAGScheduler: ResultStage 0 (collect at Tokenizer.java:83) finished in 0,434 s
17/07/21 23:58:43 INFO DAGScheduler: Job 0 finished: collect at Tokenizer.java:83, took 0,651888 s
17/07/21 23:58:44 INFO BlockManagerInfo: Removed broadcast_1_piece0 on localhost:4262 in memory (size: 1811.0 B, free: 1117.9 MB)
17/07/21 23:58:44 INFO ContextCleaner: Cleaned accumulator 1
17/07/21 23:58:44 INFO BlockManagerInfo: Removed broadcast_0_piece0 on localhost:4262 in memory (size: 9.8 KB, free: 1117.9 MB)
Either an input file or an URL must be provided!
17/07/21 23:58:49 INFO SparkContext: Invoking stop() from shutdown hook
17/07/21 23:58:49 INFO SparkUI: Stopped Spark web UI at http://192.168.188.2:4040
17/07/21 23:58:49 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/07/21 23:58:49 INFO MemoryStore: MemoryStore cleared
17/07/21 23:58:49 INFO BlockManager: BlockManager stopped
17/07/21 23:58:49 INFO BlockManagerMaster: BlockManagerMaster stopped
17/07/21 23:58:49 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/07/21 23:58:49 INFO SparkContext: Successfully stopped SparkContext
17/07/21 23:58:49 INFO ShutdownHookManager: Shutdown hook called
17/07/21 23:58:49 INFO ShutdownHookManager: Deleting directory C:\Users\VinhTL\AppData\Local\Temp\spark-6b82dd75-7fc9-44d6-8add-f2596073ec48
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 31.558s
Finished at: Fri Jul 21 23:58:50 ICT 2017
Final Memory: 12M/220M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project vn.vitk: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project vn.vitk: Command execution failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:362)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:610)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:352)
	... 21 more
```

**Comment by phuonglh** [comment]
What command leads to these errors? Are you building the JAR file or running that JAR file? It seems that you are using a wrong path for the data.

file:/F:/GitHub Reposities/vn.vitk/export/dat/tok/regexp.txt:0+942

Your title in the issue is "failed to build", but I think that's something like "failed to run". Building is very different from running. Pease read carefully the README file.

**Comment by TheVinhLuong** [comment]
It is indeed a run failure. The cause of failure is because I hadn't set the program arguments properly. Thanks for your help, it's now working.
