### ISSUE TITLE
Part-of-Speech Tagging not working

### ISSUE THREAD

**Issue by TruongQToan** [phuonglh/vn.vitk#19]
I've tried this command `./bin/spark-submit ~/vitk/target/vn.vitk-3.0.jar -t tag -a tag -i <input-file> -o <output-file>` but it does not generate output. This is the only error in the log output:

`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrameReader.load(Ljava/lang/String;)Lorg/apache/spark/sql/DataFrame;
	at vn.vitk.tag.CMMModel$CMMModelReader.load(CMMModel.java:357)
	at vn.vitk.tag.CMMModel$CMMModelReader.load(CMMModel.java:350)
	at vn.vitk.tag.CMMModel.load(CMMModel.java:339)
	at vn.vitk.tag.Tagger.load(Tagger.java:165)
	at vn.vitk.Vitk.main(Vitk.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
`

The input file is the output of segmentation tool.

> ĐOÀN 1 : ( 16 - 20 khách   đi từ 28/7/2017 – 30/7/2017 )
Ngày 1 :  
7h – 7h15 Đón xe đi đến Hạ_Long ( Vui long cho điểm đón cụ_thể )
11h30 : Đến_Hạ_Long , lên tàu và nhận phòng . Sau đó ăn trưa trên tàu
Chiều thăm quan Vịnh_Hạ_Long , Hang_Sửng_sốt   ( Tuỳ chuong trình của từng tàu khác nhau )
Ăn tối , sau đó tự_do vui_chơi trên tàu . Tham_gia các chương_trình trên tàu như   câu mực
Ngủ đêm trên tàu   4 sao - Flamingo_Cruise hoặc tương_đương
Ngày 2 :
6h – 6h30 Sáng sẽ có hoạt_động tập Tai_Chi trên bong tàu
Ăn sáng , sau đó sẽ đi thăm đảo Titop và tắm biển

Thank you very much.

**Comment by TruongQToan** [comment]
The error I mentioned above is due to inconsistent version of Spark and Hadoop. It's fixed now. Thank you.
