### ISSUE TITLE
em chào thầy. khi em thực hiện theo "Cách chạy phân đoạn từ" nó xuất hiện lỗi sau:

### ISSUE THREAD

**Issue by cuong369** [phuonglh/vn.vitk#23]
Error: Cannot load main class from JAR file:/home/cuong/vitk/target/vn.vitk-3.0.jar
Run with --help for usage help or --verbose for debug output
dưới đây là toàn bộ các thao tác thực hiện của em:
mở terminal ra nó đã có dòng sau: "bash: /usr/libexec/java_home: No such file or directory". không biết nó có ảnh hưởng đến các thao tác sau đó không !
**bash: /usr/libexec/java_home: No such file or directory
cuong@ubuntu:~/spark$ ./bin/spark-submit ~/vitk/target/vn.vitk-3.0.jar -i Q1-06-D.txt -o ma1.txt
Error: Cannot load main class from JAR file:/home/cuong/vitk/target/vn.vitk-3.0.jar
Run with --help for usage help or --verbose for debug output
cuong@ubuntu:~/spark$** 
mong thầy chỉ ra lỗi giùm em và chỉ em cách fix lỗi. Mong nhận được hồi âm sớm từ thầy.  em cảm ơn thầy

**Comment by cuong369** [comment]
bash: /usr/libexec/java_home: No such file or directory
cuong@ubuntu:~/spark$ ./bin/spark-submit ~/vitk/target/vn.vitk-3.0.jar -i Q1-06-D.txt -o ma1.txt
Error: Cannot load main class from JAR file:/home/cuong/vitk/target/vn.vitk-3.0.jar
Run with --help for usage help or --verbose for debug output
cuong@ubuntu:~/spark$

**Comment by cuong369** [comment]
> bash: /usr/libexec/java_home: No such file or directory
> cuong@ubuntu:~/spark$ ./bin/spark-submit ~/vitk/target/vn.vitk-3.0.jar -i Q1-06-D.txt -o ma1.txt
> Error: Cannot load main class from JAR file:/home/cuong/vitk/target/vn.vitk-3.0.jar
> Run with --help for usage help or --verbose for debug output
> cuong@ubuntu:~/spark$ 
>

**Comment by cuong369** [comment]
bash: /usr/libexec/java_home: No such file or directory
cuong@ubuntu:~/spark$ ./bin/spark-submit ~/vitk/target/vn.vitk-3.0.jar -i Q1-06-D.txt -o ma1.txt
```
Error: Cannot load main class from JAR file:/home/cuong/vitk/target/vn.vitk-3.0.jar
Run with --help for usage help or --verbose for debug output
cuong@ubuntu:~/spark$ 
```

**Comment by cuong369** [comment]
trong lúc mày mò em thực hiện lệnh sau:
cuong@ubuntu:~/vn.vitk$ ~/spark/bin/spark-submit --class=vn.vitk.Vitk ~/vn.vitk/target/vn.vitk-3.0.jar -i /home/Music/hello -o /home/Music/trancuong
Sau một hồi nó chạy ra các dòng rất dài thì em thử vào mục Music thì chỉ thấy tệp hello do em tạo bên trong là các file*.txt có sẵn do em tạo. Nhưng lại không hề có tệp trancuong(nó không tự tạo file này).  Trước đó em cũng thử lệnh sau:
cuong@ubuntu:~/vn.vitk$ ~/spark/bin/spark-submit --class=vn.vitk.Vitk ~/vn.vitk/target/vn.vitk-3.0.jar -i /home/Music/hello.dich1.txt -o /home/Music/trancuong.ma1/txt
Nó cũng không tạo tệp trancuong/ma1.txt. Em không biết sai ở đây. Dưới đây là các dòng hiển thị lúc chạy:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
18/06/19 13:40:41 INFO SparkContext: Running Spark version 1.6.1
18/06/19 13:40:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/06/19 13:40:43 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.56.62 instead (on interface ens33)
18/06/19 13:40:43 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
18/06/19 13:40:44 INFO SecurityManager: Changing view acls to: cuong
18/06/19 13:40:44 INFO SecurityManager: Changing modify acls to: cuong
18/06/19 13:40:44 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(cuong); users with modify permissions: Set(cuong)
18/06/19 13:40:45 INFO Utils: Successfully started service 'sparkDriver' on port 34179.
18/06/19 13:40:46 INFO Slf4jLogger: Slf4jLogger started
18/06/19 13:40:47 INFO Remoting: Starting remoting
18/06/19 13:40:47 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.0.56.62:44503]
18/06/19 13:40:47 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 44503.
18/06/19 13:40:47 INFO SparkEnv: Registering MapOutputTracker
18/06/19 13:40:47 INFO SparkEnv: Registering BlockManagerMaster
18/06/19 13:40:47 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a1825c14-3a71-4f30-bfdc-7ee9ae17ec0c
18/06/19 13:40:47 INFO MemoryStore: MemoryStore started with capacity 517.4 MB
18/06/19 13:40:48 INFO SparkEnv: Registering OutputCommitCoordinator
18/06/19 13:40:48 INFO Utils: Successfully started service 'SparkUI' on port 4040.
18/06/19 13:40:48 INFO SparkUI: Started SparkUI at http://10.0.56.62:4040
18/06/19 13:40:49 INFO HttpFileServer: HTTP File server directory is /tmp/spark-a0bebfd7-670c-482f-8c4c-5e0ebd0b6d33/httpd-b3bfacba-a028-4370-9e91-64b168fc607a
18/06/19 13:40:49 INFO HttpServer: Starting HTTP Server
18/06/19 13:40:49 INFO Utils: Successfully started service 'HTTP file server' on port 43321.
18/06/19 13:40:49 INFO SparkContext: Added JAR file:/home/cuong/vn.vitk/target/vn.vitk-3.0.jar at http://10.0.56.62:43321/jars/vn.vitk-3.0.jar with timestamp 1529440849399
18/06/19 13:40:49 INFO Executor: Starting executor ID driver on host localhost
18/06/19 13:40:49 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44261.
18/06/19 13:40:49 INFO NettyBlockTransferService: Server created on 44261
18/06/19 13:40:49 INFO BlockManagerMaster: Trying to register BlockManager
18/06/19 13:40:49 INFO BlockManagerMasterEndpoint: Registering block manager localhost:44261 with 517.4 MB RAM, BlockManagerId(driver, localhost, 44261)
18/06/19 13:40:49 INFO BlockManagerMaster: Registered BlockManager
18/06/19 13:40:52 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 127.4 KB, free 127.4 KB)
18/06/19 13:40:53 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 13.9 KB, free 141.3 KB)
18/06/19 13:40:53 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:44261 (size: 13.9 KB, free: 517.4 MB)
18/06/19 13:40:53 INFO SparkContext: Created broadcast 0 from textFile at Tokenizer.java:83
18/06/19 13:40:53 INFO FileInputFormat: Total input paths to process : 1
18/06/19 13:40:54 INFO SparkContext: Starting job: collect at Tokenizer.java:83
18/06/19 13:40:54 INFO DAGScheduler: Got job 0 (collect at Tokenizer.java:83) with 1 output partitions
18/06/19 13:40:54 INFO DAGScheduler: Final stage: ResultStage 0 (collect at Tokenizer.java:83)
18/06/19 13:40:54 INFO DAGScheduler: Parents of final stage: List()
18/06/19 13:40:54 INFO DAGScheduler: Missing parents: List()
18/06/19 13:40:54 INFO DAGScheduler: Submitting ResultStage 0 (/export/dat/tok/regexp.txt MapPartitionsRDD[1] at textFile at Tokenizer.java:83), which has no missing parents
18/06/19 13:40:54 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.1 KB, free 144.4 KB)
18/06/19 13:40:54 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 1818.0 B, free 146.2 KB)
18/06/19 13:40:54 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:44261 (size: 1818.0 B, free: 517.4 MB)
18/06/19 13:40:54 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
18/06/19 13:40:54 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (/export/dat/tok/regexp.txt MapPartitionsRDD[1] at textFile at Tokenizer.java:83)
18/06/19 13:40:54 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
18/06/19 13:40:54 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 2187 bytes)
18/06/19 13:40:54 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
18/06/19 13:40:54 INFO Executor: Fetching http://10.0.56.62:43321/jars/vn.vitk-3.0.jar with timestamp 1529440849399
18/06/19 13:40:54 INFO Utils: Fetching http://10.0.56.62:43321/jars/vn.vitk-3.0.jar to /tmp/spark-a0bebfd7-670c-482f-8c4c-5e0ebd0b6d33/userFiles-cc530866-f867-4d6d-8069-1b51559c8897/fetchFileTemp5736789801177904738.tmp
18/06/19 13:40:55 INFO Executor: Adding file:/tmp/spark-a0bebfd7-670c-482f-8c4c-5e0ebd0b6d33/userFiles-cc530866-f867-4d6d-8069-1b51559c8897/vn.vitk-3.0.jar to class loader
18/06/19 13:40:55 INFO HadoopRDD: Input split: file:/export/dat/tok/regexp.txt:0+1846
18/06/19 13:40:55 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
18/06/19 13:40:55 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
18/06/19 13:40:55 INFO deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
18/06/19 13:40:55 INFO deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
18/06/19 13:40:55 INFO deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
18/06/19 13:40:55 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 3974 bytes result sent to driver
18/06/19 13:40:55 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1494 ms on localhost (1/1)
18/06/19 13:40:56 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
18/06/19 13:40:56 INFO DAGScheduler: ResultStage 0 (collect at Tokenizer.java:83) finished in 1.589 s
18/06/19 13:40:56 INFO DAGScheduler: Job 0 finished: collect at Tokenizer.java:83, took 1.947907 s
18/06/19 13:40:58 INFO BlockManagerInfo: Removed broadcast_1_piece0 on localhost:44261 in memory (size: 1818.0 B, free: 517.4 MB)
18/06/19 13:40:58 INFO BlockManagerInfo: Removed broadcast_0_piece0 on localhost:44261 in memory (size: 13.9 KB, free: 517.4 MB)
18/06/19 13:40:58 INFO ContextCleaner: Cleaned accumulator 1
18/06/19 13:41:02 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 61.8 KB, free 61.8 KB)
18/06/19 13:41:05 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 19.3 KB, free 81.2 KB)
18/06/19 13:41:05 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on localhost:44261 (size: 19.3 KB, free: 517.4 MB)
18/06/19 13:41:05 INFO SparkContext: Created broadcast 2 from textFile at Tokenizer.java:120
18/06/19 13:41:22 ERROR FileOutputCommitter: Mkdirs failed to create file:/home/Music/trancuong.ma1.txt/_temporary/0
Exception in thread "main" org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/home/Music/hello.dich1.txt
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:285)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:228)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:313)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1922)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1213)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1156)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1156)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1156)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:1060)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:951)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1457)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1436)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1436)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1436)
	at org.apache.spark.api.java.JavaRDDLike$class.saveAsTextFile(JavaRDDLike.scala:507)
	at org.apache.spark.api.java.AbstractJavaRDDLike.saveAsTextFile(JavaRDDLike.scala:46)
	at vn.vitk.tok.Tokenizer.tokenize(Tokenizer.java:222)
	at vn.vitk.Vitk.main(Vitk.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/06/19 13:41:24 INFO SparkContext: Invoking stop() from shutdown hook
18/06/19 13:41:28 INFO SparkUI: Stopped Spark web UI at http://10.0.56.62:4040
18/06/19 13:41:30 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
18/06/19 13:41:31 INFO MemoryStore: MemoryStore cleared
18/06/19 13:41:31 INFO BlockManager: BlockManager stopped
18/06/19 13:41:31 INFO BlockManagerMaster: BlockManagerMaster stopped
18/06/19 13:41:31 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
18/06/19 13:41:32 INFO SparkContext: Successfully stopped SparkContext
18/06/19 13:41:32 INFO ShutdownHookManager: Shutdown hook called
18/06/19 13:41:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-a0bebfd7-670c-482f-8c4c-5e0ebd0b6d33/httpd-b3bfacba-a028-4370-9e91-64b168fc607a
18/06/19 13:41:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-a0bebfd7-670c-482f-8c4c-5e0ebd0b6d33
Mong nhận được sự giúp đỡ từ thầy giáo. Em cảm ơn thầy!!!

**Comment by cuong369** [comment]
em làm theo hướng dẫn tại trang: https://blog.duyet.net/2016/06/vntokenizer-tren-apache-spark.html#.WylhNaczbIV

**Comment by cuong369** [comment]
truy cập trang: http://mim.hus.vnu.edu.vn/dsl/tools/tokenizer em thấy ngoài phân đoạn từ nó còn có tác dụng: (The main class of the package is Tokenizer and its key method is segment(text). **To create a Vietnamese tokenizer** and segment a text into words, simply do as follows:) và em làm theo câu lệnh dưới thì không được. Vậy để Create a Vietnamese tokenizer thì có câu lệnh thực hiện nào khác trên cmd không ạ!!!

**Comment by phuonglh** [comment]
Nếu em mới làm quen thì em nên sử dụng bản vitk-tok-5.1 (không dùng Apache Spark ở đây)

http://mim.hus.vnu.edu.vn/dsl/tools/tokenizer

Máy của em đã cài Java chưa, em gõ lệnh sau vào Console (DOS command line) 

java -version 

thì nó ra cái gì?

Đoạn em trích ở trên là nếu em dùng trong khi lập trình, trong chương trình Java em viết sau khi đã import vitk-tok-5.1.jar, chứ không phải gõ từ command line nhé.

Từ command line thì em chỉ dùng như thế này thôi:

`java -jar vitk-tok-5.1 <inp.txt> <out.txt>`

Phương

**Comment by cuong369** [comment]
Cảm ơn thầy đã trả lời! trên ubuntu 16.04 em đã cài java rồi thầy ạ. Kết quả sau khi gõ "java -version" là:
**openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)**
Thầy ơi! Em tải về vitk-tok-5.1.jar Rồi. **_Em đã giải nén nó_**, nhưng không biết phải làm sao nữa. Sau đó em còn thử nhấp chuột phải vào tệp vừa tải về "**vitk-tok-5.1.jar**" rồi chọn "**Open With Open JDK Java 8 Runtime**". Nó ra cảnh báo "**The file '/home/cuong/Downloads/vitk-tok-5.1.jar' is not marked as executable.  If this was downloaded or copied from an untrusted source, it may be dangerous to run.  For more details, read about the executable bit**."
Em muốn hỏi là sau khi tải về thì không cần cài đặt gì nữa phải không thầy. chỉ cần mở "open terminal" ra và gõ lệnh "`java -jar vitk-tok-5.1 <inp.txt> <out.txt>` (**với inp.txt: là đường dẫn của tệp cần tách từ, còn out.txt là đường dẫn của tệp ra, và mình không cần tạo tệp ra, file xuất ra (out.txt) phải không thầy ???.**

**Comment by cuong369** [comment]
Em gõ lệnh trên thì nó ra kết quả như sau:
cuong@ubuntu:~/Downloads$ java -jar vitk-tok-5.1 ~/Music/kaka/VNTQcorpus-big.txt ~/Music/cuong369/xuat.txt
Error: Unable to access jarfile vitk-tok-5.1

**Comment by cuong369** [comment]
em cũng thử:
cuong@ubuntu:~/Downloads$ java -jar vitk-tok-5.1.jar ~/Music/kaka/VNTQcorpus-big.txt ~/Music/cuong369/xuat.txt
Nó xuất hiện lỗi:
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at java.nio.file.Files.readAllLines(Files.java:3208)
	at ai.vitk.tok.Tokenizer.main(Tokenizer.java:174)

**Comment by phuonglh** [comment]
Nếu tệp dữ liệu của em lớn thì em cần tăng kích thước bộ nhớ heap của JVM, ví dụ sử dụng 4g:

java -Xmx4g -jar vitk-tok-5.1.jar <inp.txt> <out.txt>

Chương trình chạy theo cách xử lí từng dòng của tệp input một. Thế nên em cũng nên chú ý không dùng dòng dài quá. Nếu cả tệp inp.txt chỉ có 1 dòng (vì lí do nào đó) thì chương trình sẽ tốn bộ nhớ.

**Comment by cuong369** [comment]
tức là sau khi em tải tệp vitk-tok-5.1.jar về để ở downloads thì làm theo các bước sau để tiến hành tách từ phải không ạ!
1. mở open terminal tại thư mục Downloads
2. sau khi mở xong gõ dòng lệnh: "`java -jar vitk-tok-5.1 <inp.txt> <out.txt>`" hay "`java -jar vitk-tok-5.1.jar <inp.txt> <out.txt>`" với inp.txt và out.txt phải ghi rõ đường dẫn.
3. Lưu ý với lời khuyên của thầy ở trên phải không ạ
Em cảm ơn thầy giáo!!!

**Comment by cuong369** [comment]
em gõ như sau:
cuong@ubuntu:~/Downloads$ java -Xmx4g -jar vitk-tok-5.1.jar ~/Music/kaka/VNTQcorpus-big.txt ~/Music/cuong369/xuat.txt
Nhưng mà nó không xử lý gì hết. có hiện tượng hơi đơ đơ (hay cái này do nó đang xử lý) thầy ạ!

**Comment by phuonglh** [comment]
Trong lệnh 2, em cần sử dụng "vitk-tok-5.1.jar", với đuôi jar ở cuối. 

Em nên test thử với 1 tệp nhỏ, lấy tệp inp.txt chứa vài chục hoặc vài trăm dòng (chép từ 1 trang báo chẳng hạn) rồi thử xem có chạy được không đã, trước khi chạy ngay 1 tệp lớn. 

Nếu máy của em có ít RAM (4g chẳng hạn) thì không nên dùng 4g RAM như em làm ở trên, máy sẽ bị đơ khi hết bộ nhớ.

**Comment by cuong369** [comment]
dạ. em sẽ test thử bản text nhỏ hơn. rất cảm ơn thầy. mong thầy có thêm thật nhiều sức khoẻ, hạnh phúc và thành công trong cuộc sống.

**Comment by cuong369** [comment]
thầy ơi!!!
em tạo 1 file tên là **dịch1.txt** trong file "**hihihi**" với nội dung sau:
nam, hy huy vvv...
tiếp đó khi không tạo tệp đầu ra thì nó báo lỗi (em tưởng nó tự tạo tệp). Sau đó em tạo tệp đầu ra "**cuong369**" và gõ lệnh: "**cuong@ubuntu:~/Downloads$ java -jar vitk-tok-5.1.jar ~/Music/hihihi/dich1.txt ~/Music/cuong369/xuat.txt**"
Khi chạy xong. kiểm tra nội dung tệp xuat.txt thì em thấy nó sai thì phải:
nội dụng như sau:
nam/WORD ,/PUNCT hy/WORD huy/WORD vvv/WORD .../PUNCT
đáng nhé nội dung phải như thế này phải ko thầy: nam , hy huy vvv ...( trước đó là: nam, hy huy vvv...).
em ko biết đúng chưa? mong thầy xem giúp em. em cảm ơn thầy

**Comment by phuonglh** [comment]
Không sai đâu em. Kết quả mặc định ở dạng 

từ/FORM

Nếu em không dùng tệp <out.txt> thì chương trình in kết quả ra màn hình, định dạng cũng khác. Còn nếu không dùng cả tệp inp.txt thì chương trình tách dòng nhập vào từ bàn phím (kết thúc bằng dòng trắng).

Em có thể test online công cụ tách từ ở đây: http://vlsp.org.vn:8080/vitk/tok/index.xhtml

Nếu em muốn kết xuất ra kết quả với định dạng khác thì cần lập trình.

**Comment by cuong369** [comment]
dạ vâng. với trường hợp em muốn làm trên cả tệp chứ không chọn cụ thể từng bản txt trong tệp mẹ. thì có được không thầy. em đã thử
java -jar vitk-tok-5.1.jar ~/Music/hihihi ~/Music/cuong369
nhưng nó báo lỗi:
Exception in thread "main" java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.nio.file.Files.readAllLines(Files.java:3205)
	at ai.vitk.tok.Tokenizer.main(Tokenizer.java:174)

**Comment by phuonglh** [comment]
Hiện tại chương trình không hỗ trợ tách từ 1 thư mục. Em có thể tự làm điều đó bằng cách lập trình thêm: liệt kê các tệp trong thư mục, gọi chương trình tách từ trên từng tệp đó.

**Comment by cuong369** [comment]
Dạ vâng. em cảm ơn thầy. chúc thầy giáo có thật nhiều sức khoẻ, hạnh phúc và thành công trong cuộc sống. Em chào thầy!!!
