### ISSUE TITLE
Lỗi khi chạy tagging 

### ISSUE THREAD

**Issue by manhtuhtk** [phuonglh/vn.vitk#7]
Chào anh, em chạy thử thư viện của anh trên spark cloud với command như sau:

 `spark-submit vn.vitk/target/vn.vitk-3.0.jar -t tag -i /regang/tag/test1.txt -o /regang/tag/test1.tag`

File dữ liệu test
[test1.txt](https://github.com/phuonglh/vn.vitk/files/406911/test1.txt)

thì thấy có lỗi này xuất hiện
16/08/09 04:33:03 INFO spark.SparkContext: Created broadcast 0 from textFile at ReadWrite.scala:285
16/08/09 04:33:04 INFO mapred.FileInputFormat: Total input paths to process : 0
Exception in thread "main" java.lang.UnsupportedOperationException: empty collection
        at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1344)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
        at org.apache.spark.rdd.RDD.first(RDD.scala:1341)
        at org.apache.spark.ml.util.DefaultParamsReader$.loadMetadata(ReadWrite.scala:285)
        at org.apache.spark.ml.util.DefaultParamsReader.loadMetadata(ReadWrite.scala)
        at vn.vitk.tag.CMMModel$CMMModelReader.load(CMMModel.java:353)
        at vn.vitk.tag.CMMModel$CMMModelReader.load(CMMModel.java:350)
        at vn.vitk.tag.CMMModel.load(CMMModel.java:339)
        at vn.vitk.tag.Tagger.load(Tagger.java:165)
        at vn.vitk.Vitk.main(Vitk.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/08/09 04:33:04 INFO spark.SparkContext: Invoking stop() from shutdown hook
16/08/09 04:33:04 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/static/sql,null}
16/08/09 04:33:04 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/SQL/execution/json,null}

**Comment by phuonglh** [comment]
Hello,

Có vẻ lỗi phát sinh trong quá trình Vitk nạp tagging model. Bạn đã chép dữ liệu cho tag vào thư mục `/export/dat/tag` chưa?

Trước khi chạy tagging, bạn đã chạy được tách từ với Vitk rồi chứ?

**Comment by manhtuhtk** [comment]
Em đã copy model vào `/export/dat/tag` rồi, bằng lệnh sau
`hdfs dfs -copyFromLocal vn.vitk/dat/* /export/`

Em cũng đã chạy thử với segmentation thì có output, nhưng chạy với tagging vẫn bị lỗi như trên!

**Comment by phuonglh** [comment]
Em thử copy không phải bằng hdfs mà chỉ đơn giản bằng lệnh cp của hệ điều hành rồi chạy trên local thôi xem có được không?

`cp vn.vitk/dat/* /export/dat`

Rồi em kiểm tra lại xem có thư mục `/export/dat/tag/vi/cmm` hay không.

Lỗi ở trên nói là không tìm thấy tệp nào để đọc.

**Comment by phuonglh** [comment]
Mình bổ sung thêm là tệp để gãn nhãn hiện có yêu cầu là dữ liệu cần được tách từ trước rồi nhé. Tệp "test1.txt" của em chưa được tách từ nên gán nhãn sẽ không chính xác đâu. Trong phiên bản tới khi người dùng chọn tagging thì Vitk sẽ có option cho phép chỉ định dữ liệu vào đã tách từ hay chưa.

**Comment by manhtuhtk** [comment]
Em tạo thư mục local chạy vẫn ra lỗi trên, sau khi xem `CMMModelReader.java` em đoán là models phải load từ hdfs, khi copy dữ liệu lên hdfs để ý thì thấy có lỗi checksum (vì có các file hidden `.*.crc` trong thư mục `vn.vitk/dat/`) nên gây thiếu file và gây ra lỗi trên.

Các file hidden có thể liệt kê bằng `find vn.vitk/dat/ -name ".*" -print`

Để fix lỗi trên thì xóa các file ẩn kia `find vn.vitk/dat/ -name ".*" -exec rm -f {} \;`
Rồi copy `vn.vitk/dat/*` lên hdfs và chạy như hướng dẫn sẽ không gặp lỗi.

Cảm ơn anh đã phản hồi nhanh chóng, thư viện NLP này của anh rất hữu ích ạ, mong rằng trong version tiếp theo sẽ có các cải tiến mới, nhất là về DEP :)
