### ISSUE TITLE
Lỗi khi chạy tagging trên hadoop

### ISSUE THREAD

**Issue by mvn-khoadao-hn** [phuonglh/vn.vitk#9]
Hi anh,

Em chạy vn.vitk ở PC của em rất ok, nhưng sau đó đưa lên server chạy hadoop thì gặp lỗi này, rất mong anh giúp đỡ ạ 

16/10/24 09:28:28 WARN org.apache.parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
16/10/24 09:28:28 INFO org.apache.parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 1 records.
16/10/24 09:28:28 INFO org.apache.parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
16/10/24 09:28:28 INFO org.apache.hadoop.io.compress.zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
16/10/24 09:28:28 INFO org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.gz]
16/10/24 09:28:28 INFO org.apache.parquet.hadoop.InternalParquetRecordReader: block read in memory in 26 ms. row count = 1
16/10/24 09:28:28 INFO org.apache.hadoop.mapred.FileInputFormat: Total input paths to process : 1
16/10/24 09:28:28 INFO org.apache.hadoop.mapred.FileInputFormat: Total input paths to process : 1
16/10/24 09:28:29 INFO org.apache.parquet.hadoop.ParquetFileReader: Initiating action with parallelism: 5
16/10/24 09:28:29 WARN org.apache.parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
16/10/24 09:28:29 INFO org.apache.parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 1 records.
16/10/24 09:28:29 INFO org.apache.parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
16/10/24 09:28:29 INFO org.apache.parquet.hadoop.InternalParquetRecordReader: block read in memory in 2 ms. row count = 1
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrameReader.load(Ljava/lang/String;)Lorg/apache/spark/sql/DataFrame;
    at vn.vitk.tag.CMMModel$CMMModelReader.load(CMMModel.java:357)
    at vn.vitk.tag.CMMModel$CMMModelReader.load(CMMModel.java:350)
    at vn.vitk.tag.CMMModel.load(CMMModel.java:339)
    at vn.vitk.tag.Tagger.load(Tagger.java:165)
    at vn.vitk.Vitk.main(Vitk.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by phuonglh** [comment]
Anh nghĩ là có lỗi không tương thích giữa các version của thư viện trên Hadoop. Em kiểm tra xem version của spark-avro xem thế nào? 

Có vẻ nó giống lỗi này mà một số người đã gặp: https://github.com/databricks/spark-avro/issues/150

**Comment by mvn-khoadao-hn** [comment]
Cảm ơn anh đã support ạ, đúng là chuyển dùng spark v1.6.2 trên hadoop là chạy ok. Trước đây spark v2.0.0 có lẽ có vấn đề khi cài đặt nên ko tương thích.
